CREATE PROCEDURE CREATE_ARCH_TABLE_RESERVATIONS
	@ERROR_CODE	INT	OUTPUT,
	@ERROR_MSG NVARCHAR(MAX) OUTPUT
AS
BEGIN TRY
	DECLARE @SQL_QUERY		NVARCHAR(MAX)
	DECLARE @YYYYMM			NVARCHAR(6)
	DECLARE @ARH_TABLE_NAME NVARCHAR(32)
	DECLARE @MONTH			NVARCHAR(2) = MONTH( GETDATE() )

	SET @MONTH = IIF( LEN( @MONTH ) < 2, 
						CONCAT( N'0', @MONTH), 
						@MONTH )

	SET @YYYYMM  =  CONCAT( YEAR(GETDATE()), @MONTH)
    SET @ARH_TABLE_NAME = CONCAT( N'RESERVATIONS_', @YYYYMM )

   IF NOT EXISTS ( SELECT * 
				   FROM SYS.TABLES 
				   WHERE NAME = @ARH_TABLE_NAME)
    BEGIN
        SET @SQL_QUERY = N' CREATE TABLE @@ARH_TABLE_NAME@@
							(
								ID					SMALLINT		NOT NULL,
								[STATUS]			VARBINARY		NOT NULL,
								RESTAURANT_ID		SMALLINT		NOT NULL,
								CLIENT_ID			SMALLINT		NOT NULL,
								REG_DATE			DATETIME		NOT NULL,
								RESERVATION_DATE	DATETIME		NOT NULL,
								STATUS_CHANGE_DATE	DATETIME		NOT NULL,
								LOCATION_ID			SMALLINT		NOT NULL,
								TABLE_TYPE_ID		SMALLINT		NOT NULL,
								NUMBER_PEOPLE		SMALLINT		NOT NULL,
								DURATION			FLOAT			NOT NULL,
								POINTS_USED			SMALLINT		NOT NULL,
								NOTE				NVARCHAR(510)	NOT NULL,

								PRIMARY KEY(ID)
							)
							CREATE INDEX IX_@@ARH_TABLE_NAME@@_CLIENT				 ON RESERVATIONS(CLIENT_ID)
							CREATE INDEX IX_@@ARH_TABLE_NAME@@_RESTAURANT			 ON RESERVATIONS(RESTAURANT_ID)
							CREATE INDEX IX_@@ARH_TABLE_NAME@@_RESTAURANT_RES_DATE   ON RESERVATIONS(RESTAURANT_ID,RESERVATION_DATE)'

		SET @SQL_QUERY = REPLACE(@SQL_QUERY, N'@@ARH_TABLE_NAME@@', @ARH_TABLE_NAME)

		EXEC sp_executesql @SQL_QUERY;
	END
END TRY
BEGIN CATCH
	DECLARE @ErrorMessage NVARCHAR(MAX) = ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
    DECLARE @ErrorState INT = ERROR_STATE();

	RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);
    RETURN
END CATCH
GO