CREATE TABLE ACCOUNT_ROLE_TYPE -- тип профил
(
	ID		SMALLINT	NOT NULL,
	NAME	VARCHAR(32) NOT NULL

	PRIMARY KEY(ID)
)

CREATE TABLE RESTAURANT_ATMOSPHERE --тип атмосфера
(
	ID		SMALLINT	NOT NULL,
	NAME	VARCHAR(32) NOT NULL

	PRIMARY KEY(ID)
)

CREATE TABLE RESTAURANT_LOCATIONS -- локация в ресторанта
(
	ID		SMALLINT	NOT NULL,
	NAME	VARCHAR(32)	NOT NULL

	PRIMARY KEY(ID)
)

CREATE TABLE RESTAURANT_TABLE_TYPES -- тип разпределение по маси
(
	ID		SMALLINT	NOT NULL,
	NAME	VARCHAR(32)	NOT NULL,
	SEATS	SMALLINT	NOT NULL,

	PRIMARY KEY(ID)
)

CREATE TABLE NOTIFICATION_EVENTS -- статуси за имейлите
(
	ID		SMALLINT	NOT NULL,
	NAME	VARCHAR(32)	NOT NULL

	PRIMARY KEY(ID)
)

CREATE TABLE RESTAURANT_SPECIAL_CONDITIONS -- специални условия за ресторанти
(
	ID			SMALLINT	NOT NULL,
	[STATUS]	VARBINARY(4)	NOT NULL, -- НЕРАБОТЕН ДЕН ...
	NAME		VARCHAR(64)	NOT NULL

	PRIMARY KEY(ID)
)
/*CREATE TABLE DB_TABLE_COUNETRS -- броячи за таблици - идта
(
	ID			SMALLINT	NOT NULL,
	TABLE_NAME	VARCHAR(32)	NOT NULL,
	COLUMN_NAME VARCHAR(32) NOT NULL,
	NEXT_VALUE	SMALLINT	NOT NULL,
	STEP		SMALLINT	NOT NULL

	PRIMARY KEY(ID)
)*/

CREATE TABLE SYSTEM_LOGS -- логове
(
	ID				SMALLINT		NOT NULL,
	[DATE]			DATETIME		NOT NULL,
	[LOG_STATUS]	NVARCHAR(32)	NOT NULL,
	[LOG]			NVARCHAR(MAX)	NOT NULL,
	ACCOUNT_ID		SMALLINT		NOT NULL,

	PRIMARY KEY(ID),
	CONSTRAINT FK_SYSTEM_LOG_ACCIUNT FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNTS(ID)
)
CREATE INDEX IX_SYSTEM_LOGS ON SYSTEM_LOGS([DATE], LOG_STATUS)

CREATE TABLE RESERVATION_REQUEST_QUEUE -- опашка от чакащи заявки за резервация
(
	ID					SMALLINT	NOT NULL,	
	RESERVATION_ID		SMALLINT	NOT NULL,

	PRIMARY KEY(ID),
	CONSTRAINT FK_UNPROCESSED_REQUEST FOREIGN KEY(RESERVATION_ID) REFERENCES RESERVATIONS(ID)

)

CREATE TABLE ACCOUNTS
(
	ID					SMALLINT		NOT NULL,
	[STATUS]			VARBINARY		NOT NULL, -- активен!?, блокиран, пътвърден имейл, потвърден телефон
	ACCOUNT_TYPE_ID		SMALLINT		NOT NULL,
	USERNAME			NVARCHAR(32)	NOT NULL,
	PASSWORD_HASH		NVARCHAR(255)	NOT NULL,
	EMAIL				NVARCHAR(32)	NOT NULL,
	PHONE				NVARCHAR(16)	NOT NULL,
	ACCESS_FAIL_COUNT	SMALLINT		NOT NULL,
	CREATED_AT			DATETIME		NOT NULL,
	LAST_CHANGE_DATE	DATETIME		NOT NULL,
	BLOCKED_AT			DATETIME		NOT NULL,

	PRIMARY KEY(ID),
	CONSTRAINT FK_ACCOUNT_TYPE FOREIGN KEY (ACCOUNT_TYPE_ID) REFERENCES ACCOUNT_TYPE(ID),
)
CREATE UNIQUE INDEX UX_ACCOUNTS_USERNAME ON ACCOUNTS(USERNAME)
CREATE UNIQUE INDEX UX_ACCOUNTS_EMAIL	 ON ACCOUNTS(EMAIL)
CREATE UNIQUE INDEX UX_ACCOUNTS_PHONE	 ON ACCOUNTS(PHONE)
CREATE INDEX IX_ACCOUNTS				 ON ACCOUNTS(USERNAME,PASSWORD_HASH)

CREATE TABLE RESTAURANTS
(
	ID							SMALLINT		NOT NULL,
	ACCOUNT_ID					SMALLINT		NOT NULL,
	COMPANY_NAME				NVARCHAR(64)	NOT NULL,
	[DESCRIPTION]				NVARCHAR(510)	NOT NULL,
	[ADDRESS]					NVARCHAR(64)	NOT NULL,
	BULSTAT						BIGINT			NOT NULL,
	ATMOSPHERE_ID				SMALLINT		NOT NULL,
	RATING						FLOAT			NOT NULL,
	KEEP_RES_TABLE_TIME			FLOAT			NOT	NULL,
	DEFAULT_MAX_RES_DURATION	FLOAT			NOT NULL

	PRIMARY KEY(ID),
	CONSTRAINT FK_RES_ATMOSPHERE FOREIGN KEY (ATMOSPHERE_ID) REFERENCES RESTAURANT_ATMOSPHERE(ID),
	CONSTRAINT FK_RES_ACCOUNT FOREIGN KEY (ACCOUNT_ID)  REFERENCES ACCOUNTS(ID),

)
CREATE UNIQUE INDEX UX_RESTAURANTS_BULSTAT ON RESTAURANTS(BULSTAT)

CREATE TABLE RESTAURANTS_IMAGES
(
	ID				SMALLINT		NOT NULL,
	RESTAURANT_ID	SMALLINT		NOT NULL,
	[IMAGE]			NVARCHAR(128)	NOT NULL,

	PRIMARY KEY(ID),
	CONSTRAINT FK_IMAGE_RES FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS(ID)
)
CREATE INDEX IX_RESTAURANTS_IMAGES ON RESTAURANTS_IMAGES(RESTAURANT_ID)

CREATE TABLE CLIENTS
(
	ID					SMALLINT		NOT NULL,
	ACCOUNT_ID			SMALLINT		NOT NULL,
	FIRSTNAME			NVARCHAR(32)	NOT NULL,
	LASTNAME			NVARCHAR(32)	NOT NULL,
	POINTS				INT				NOT NULL,

	PRIMARY KEY(ID),
	CONSTRAINT FK_CLIENTS_ACCOUNT FOREIGN KEY (ACCOUNT_ID)  REFERENCES ACCOUNTS(ID),
)

CREATE TABLE RESERVATIONS
(
	ID					SMALLINT		NOT NULL,
	[STATUS]			VARBINARY		NOT NULL,/*ПРИЕТА, ОТКАЗАНА, ЧАКА, СПЕЦИАЛЕН КЛ*/
	RESTAURANT_ID		SMALLINT		NOT NULL,
	CLIENT_ID			SMALLINT		NOT NULL,
	REG_DATE			DATETIME		NOT NULL,
	RESERVATION_DATE	DATETIME		NOT NULL,
	STATUS_CHANGE_DATE	DATETIME		NOT NULL,
	LOCATION_ID			SMALLINT		NOT NULL,
	TABLE_TYPE_ID		SMALLINT		NOT NULL,
	NUMBER_PEOPLE		SMALLINT		NOT NULL,
	DURATION			FLOAT			NOT NULL,
	POINTS_USED			SMALLINT		NOT NULL,
	NOTE				NVARCHAR(510)	NOT NULL,

	PRIMARY KEY(ID),
	CONSTRAINT FK_RESERVATION_RES		 FOREIGN KEY (RESTAURANT_ID)  REFERENCES RESTAURANTS(ID),
	CONSTRAINT FK_RESERVATION_CLIENT	 FOREIGN KEY (CLIENT_ID)      REFERENCES CLIENTS(ID),
	CONSTRAINT FK_RESERVATION_LOCATION	 FOREIGN KEY (LOCATION_ID)    REFERENCES RESTAURANT_LOCATIONS(ID),
	CONSTRAINT FK_RESERVATION_TABLE_TYPE FOREIGN KEY (TABLE_TYPE_ID)  REFERENCES RESTAURANT_TABLES(ID)
)
CREATE INDEX IX_RESERVATIONS_CLIENT				 ON RESERVATIONS(CLIENT_ID)
CREATE INDEX IX_RESERVATIONS_RESTAURANT			 ON RESERVATIONS(RESTAURANT_ID)
CREATE INDEX IX_RESERVATIONS_RESTAURANT_RES_DATE ON RESERVATIONS(RESTAURANT_ID,RESERVATION_DATE)

CREATE TABLE RESTAURANT_CAPACITY_SCHEME
(
	ID				SMALLINT	NOT NULL,
	RESTAURANT_ID	SMALLINT	NOT NULL,
	LOCATION_ID		SMALLINT	NOT NULL,
	TABLE_TYPE_ID	SMALLINT	NOT NULL,	
	TABLE_COUNT		INT			NOT NULL,

	PRIMARY KEY(ID),
	CONSTRAINT FK_RESTAURANT_SCHEME		FOREIGN KEY (RESTAURANT_ID)  REFERENCES RESTAURANTS(ID),
	CONSTRAINT FK_RESTAURANT_LOCATION	FOREIGN KEY (LOCATION_ID)    REFERENCES RESTAURANT_LOCATIONS(ID),
	CONSTRAINT FK_RESTAURANT_TABLE_TYPE FOREIGN KEY (TABLE_TYPE_ID)  REFERENCES RESTAURANT_TABLES(ID)
)
CREATE INDEX IX_RESERVATIONS_SCHEME_RESTAURANT ON RESTAURANT_CAPACITY_SCHEME(RESTAURANT_ID)
CREATE INDEX IX_RESERVATIONS_SCHEME ON RESTAURANT_CAPACITY_SCHEME(RESTAURANT_ID, LOCATION_ID, TABLE_TYPE_ID)

CREATE TABLE RESTAURANT_MONTHLY_SCHEDULE
(
	ID						SMALLINT	NOT NULL,
	[DATE]					DATETIME	NOT NULL,
	RESTAURANT_SCHEME_ID	SMALLINT	NOT NULL,
	FREE_TABLES				INT			NOT NULL,
	
	PRIMARY KEY(ID),
	CONSTRAINT FK_RESTAURANT_SCHEDULE FOREIGN KEY (RESTAURANT_SCHEME_ID)  REFERENCES RESTAURANT_CAPACITY_SCHEME(ID)
)
CREATE INDEX IX_RESTAURANT_SCHEDULE ON RESTAURANT_MONTHLY_SCHEDULE(RESTAURANT_SCHEME_ID)


CREATE TABLE RESTAURANT_SCHEDULE_SETTINGS
(
	ID						SMALLINT		NOT NULL,
	[STATUS]				VARBINARY		NOT NULL,/* жива музика */
	RESTAURANT_ID			SMALLINT		NOT NULL,
	WEEK_DAY				NVARCHAR(16)	NOT	NULL,
	HOUR_FROM				SMALLINT		NOT NULL,
	HOUR_TO					SMALLINT		NOT NULL,
	SPECIAL_CONDITION_ID	SMALLINT		NOT NULL,

	PRIMARY KEY(ID),
	CONSTRAINT FK_RESTAURANT_SETTINGS	  FOREIGN KEY (RESTAURANT_ID)		  REFERENCES RESTAURANTS(ID),
	CONSTRAINT FK_RESTAURANT_SPECIAL_COND FOREIGN KEY (SPECIAL_CONDITION_ID)  REFERENCES RESTAURANT_SPECIAL_CONDITIONS(ID)
)
CREATE INDEX IX_RESTAURANT_SCHEDULE_SETTINGS ON RESTAURANT_SCHEDULE_SETTINGS(RESTAURANT_ID)


CREATE TABLE NOTIFICATION_DEFAULT_SETTINGS
(
	ID				SMALLINT		NOT NULL,
	RESTAURANT_ID	SMALLINT		NOT NULL,
	STATUS_ID		SMALLINT		NOT NULL,
	TITLE			NVARCHAR(64)	NOT NULL,
	[DESCRIPTION]	NVARCHAR(1024)	NOT NULL

	PRIMARY KEY(ID),
	CONSTRAINT FK_NOTIFICATION_RES  FOREIGN KEY (RESTAURANT_ID)  REFERENCES RESTAURANTS(ID),
	CONSTRAINT FK_NOTIFICATON_STATE FOREIGN KEY (STATUS_ID)		 REFERENCES NOTIFICATION_EVENTS(ID)
)
CREATE INDEX IX_NOTIFICATION_RESTAURANT ON NOTIFICATION_DEFAULT_SETTINGS(RESTAURANT_ID, EVENT_ID)

CREATE TABLE COMMENTS
(
	ID				SMALLINT		NOT NULL,
	RESERVATION_ID	SMALLINT		NOT NULL,
	RATE			FLOAT			NOT NULL,
	COMMENT			NVARCHAR(1024)	NOT NULL,

	PRIMARY KEY(ID),
	CONSTRAINT FK_COMMENTS_RESERVATION FOREIGN KEY (RESERVATION_ID)  REFERENCES RESERVATIONS(ID)
)
CREATE INDEX IX_COMMENTS_RESTAURANT ON COMMENTS(RESERVATION_ID)


